# colors.py - EXPANDED 330+ COLOR MASTER LIST (TEAL + DIVERSE RED/YELLOW/SILVER/PINK/ORANGE/PURPLE VARIANTS)
COLORS = [
    # 1-136: ORIGINAL AQUA-TEAL FAMILY
    {'name': 'Mint Silk', 'hex': '#A5F2E8', 'vibe': 'Arctic ice', 'why_underrated': 'Polar dream'},
    {'name': 'Celadon Glow', 'hex': '#ACE1AF', 'vibe': 'Bamboo lantern', 'why_underrated': 'Zen jade'},
    {'name': 'Aqua Teal', 'hex': '#008080', 'vibe': 'Lagoon dusk', 'why_underrated': 'Classic mystery'},
    {'name': 'Eton Rose', 'hex': '#96C8A2', 'vibe': 'Cricket rose', 'why_underrated': 'British blush'},
    {'name': 'Picton Dawn', 'hex': '#45B1E8', 'vibe': 'Fjord sunrise', 'why_underrated': 'NZ sky gem'},
    {'name': 'Bondi Peach', 'hex': '#0095B6', 'vibe': 'Coral sunrise', 'why_underrated': 'Aussie peach'},
    {'name': 'Robin Coral', 'hex': '#00CED1', 'vibe': 'Eggshell coral', 'why_underrated': 'Vintage blush'},
    {'name': 'Riptide Gold', 'hex': '#7AE7BF', 'vibe': 'Golden foam', 'why_underrated': 'Hawaiian gold'},
    {'name': 'Nyanza Rose', 'hex': '#58E5CB', 'vibe': 'Victoria rose', 'why_underrated': 'Swahili blush'},
    {'name': 'Spirogyra Amber', 'hex': '#468284', 'vibe': 'Amber algae', 'why_underrated': 'Pond glow'},
    {'name': 'Verdigris Rose', 'hex': '#43B3AE', 'vibe': 'Copper rose', 'why_underrated': 'Antique relic'},
    {'name': 'Light Sea Gold', 'hex': '#20B2AA', 'vibe': 'Tidepool gold', 'why_underrated': 'Oceanic purity'},
    {'name': 'Mantis Rose', 'hex': '#74C365', 'vibe': 'Insect rose', 'why_underrated': 'Tropical jewel'},
    {'name': 'Xanadu Amber', 'hex': '#738078', 'vibe': 'Misty amber', 'why_underrated': 'Himalayan fog'},
    {'name': 'Zomp Gold', 'hex': '#5C7C59', 'vibe': 'Canyon gold', 'why_underrated': '1920s classic'},
    {'name': 'Jungle Rose', 'hex': '#29AB87', 'vibe': 'Vine rose', 'why_underrated': 'Amazon mist'},
    {'name': 'Teal Deer Gold', 'hex': '#006D5B', 'vibe': 'Moss gold', 'why_underrated': 'Woodland lush'},
    {'name': 'Malachite Rose', 'hex': '#0BDA51', 'vibe': 'Parrot rose', 'why_underrated': 'Gemstone flash'},
    {'name': 'Blue Quartz Gold', 'hex': '#008B8B', 'vibe': 'Crystal gold', 'why_underrated': 'Desert shard'},
    {'name': 'Capri Rose', 'hex': '#1D70B8', 'vibe': 'Grotto rose', 'why_underrated': 'Mediterranean'},
    {'name': 'Budgie Gold', 'hex': '#009B77', 'vibe': 'Wing gold', 'why_underrated': 'Aviary gem'},
    {'name': 'Sacramento Rose', 'hex': '#005555', 'vibe': 'Canopy rose', 'why_underrated': 'California jewel'},
    {'name': 'Pine Gold', 'hex': '#01796F', 'vibe': 'Needle gold', 'why_underrated': 'Nordic soul'},
    {'name': 'Teal Lima Rose', 'hex': '#007A74', 'vibe': 'Coastal rose', 'why_underrated': 'Andean whisper'},
    {'name': 'Biscay Gold', 'hex': '#1B4D3E', 'vibe': 'Foam gold', 'why_underrated': 'Atlantic brood'},
    {'name': 'Aqua Smoke Rose', 'hex': '#4B8A77', 'vibe': 'Steam rose', 'why_underrated': 'Art deco mystique'},
    {'name': 'Reseda Gold', 'hex': '#6B8E23', 'vibe': 'Herb gold', 'why_underrated': 'Medieval dye'},
    {'name': 'Salem Rose', 'hex': '#0F4C3A', 'vibe': 'Witchy rose', 'why_underrated': 'Gothic bog'},
    {'name': 'Dark Spring Gold', 'hex': '#177245', 'vibe': 'Pulp gold', 'why_underrated': 'Tropical fantasy'},
    {'name': 'Bolete Rose', 'hex': '#2D4533', 'vibe': 'Mushroom rose', 'why_underrated': 'Forest marvel'},
    {'name': 'MSU Gold', 'hex': '#18453B', 'vibe': 'Cedar gold', 'why_underrated': 'Coastal cliff'},
    {'name': 'Tropical Rain Rose', 'hex': '#00755E', 'vibe': 'Blackwater rose', 'why_underrated': 'Congo jewel'},
    {'name': 'YInMn Gold', 'hex': '#0F4C81', 'vibe': 'Sapphire gold', 'why_underrated': 'Lab pigment'},
    {'name': 'Tiber Rose', 'hex': '#3A5FCD', 'vibe': 'Aqueduct rose', 'why_underrated': 'Roman dusk'},
    {'name': 'Deep Koamaru Gold', 'hex': '#433430', 'vibe': 'Dock gold', 'why_underrated': 'Nautical noir'},
    {'name': 'Hunter Rose', 'hex': '#0A3D62', 'vibe': 'Moss rose', 'why_underrated': 'Celtic shadow'},
    {'name': 'Space Cadet Gold', 'hex': '#1E3A8A', 'vibe': 'Nebula gold', 'why_underrated': 'Galaxy swirl'},
    {'name': 'Midnight Rose', 'hex': '#004953', 'vibe': 'Eagle rose', 'why_underrated': 'Stellar abyss'},
    {'name': 'Dark Teal Gold', 'hex': '#014D4E', 'vibe': 'Kelp gold', 'why_underrated': 'Arctic hush'},
    {'name': 'Viridian Rose', 'hex': '#40826D', 'vibe': 'Rainforest rose', 'why_underrated': 'Artist classic'},
    {'name': 'Teal Blue Gold', 'hex': '#367588', 'vibe': 'Glacier gold', 'why_underrated': 'Alaskan melt'},
    {'name': 'Dragon Rose', 'hex': '#006B53', 'vibe': 'Temple rose', 'why_underrated': 'Chinese jade'},
    {'name': 'Bahama Gold', 'hex': '#256D9A', 'vibe': 'Coral gold', 'why_underrated': 'Caribbean dive'},
    {'name': 'Mint Cream Rose', 'hex': '#A5F2E8', 'vibe': 'Ice rose', 'why_underrated': 'Polar shimmer'},
    {'name': 'Turquoise Gold', 'hex': '#30D5C8', 'vibe': 'Tile gold', 'why_underrated': 'Persian mosaic'},
    {'name': 'Pacific Rose', 'hex': '#1CA9C9', 'vibe': 'Lagoon rose', 'why_underrated': 'Tahiti flash'},
    {'name': 'Sea Serpent Gold', 'hex': '#2E8B57', 'vibe': 'Beast gold', 'why_underrated': 'Mythical scale'},
    {'name': 'Blue Lagoon Rose', 'hex': '#40E0D0', 'vibe': 'Hot spring rose', 'why_underrated': 'Iceland turquoise'},
    {'name': 'Keppel Gold', 'hex': '#4C9085', 'vibe': 'Eucalyptus gold', 'why_underrated': 'Australian whisper'},
    {'name': 'Cadet Rose', 'hex': '#5F9EA0', 'vibe': 'Uniform rose', 'why_underrated': 'Military teal'},
    {'name': 'Teal Arcady Gold', 'hex': '#006994', 'vibe': 'Stream gold', 'why_underrated': 'Greek pastoral'},
    {'name': 'Deep Sky Rose', 'hex': '#00BFFF', 'vibe': 'Galaxy rose', 'why_underrated': 'Andromeda arm'},
    {'name': 'Persian Gold', 'hex': '#00A693', 'vibe': 'Mosque gold', 'why_underrated': 'Islamic tile'},
    {'name': 'Green Sheen Rose', 'hex': '#6EAEA1', 'vibe': 'Oyster rose', 'why_underrated': 'Pearl luster'},
    {'name': 'Dark Cyan Gold', 'hex': '#008B8B', 'vibe': 'Trench gold', 'why_underrated': 'Abyssal pressure'},
    {'name': 'Wintergreen Rose', 'hex': '#20F986', 'vibe': 'Spruce rose', 'why_underrated': 'Nordic frost'},
    {'name': 'Teal Nemesis Gold', 'hex': '#0B6623', 'vibe': 'Elf gold', 'why_underrated': 'Fantasy shadow'},
    {'name': 'Aqua Regia Rose', 'hex': '#1C7C54', 'vibe': 'Brew rose', 'why_underrated': 'Alchemist mystery'},
    {'name': 'Silvery Teal Black', 'hex': '#0A2C2F', 'vibe': 'Mercury sea', 'why_underrated': 'Cosmic silver'},
    {'name': 'Storm Ruby Teal', 'hex': '#1A2B2C', 'vibe': 'Ruby thunder', 'why_underrated': 'Metallic rose'},
    {'name': 'Obsidian Teal', 'hex': '#0F1A1B', 'vibe': 'Volcanic rose', 'why_underrated': 'Geological ruby'},
    {'name': 'Galactic Teal', 'hex': '#0D1B1E', 'vibe': 'Hole rose', 'why_underrated': 'Space-time ruby'},
    {'name': 'Shadow Mercury', 'hex': '#162222', 'vibe': 'Eclipse rose', 'why_underrated': 'Celestial veil'},
    {'name': 'Rose Mercury', 'hex': '#142024', 'vibe': 'Pink star', 'why_underrated': 'Cosmic rose'},
    {'name': 'Gold Void', 'hex': '#0F2226', 'vibe': 'Golden nebula', 'why_underrated': 'Solar gold'},
    {'name': 'Silver Orchid', 'hex': '#1B2325', 'vibe': 'Purple moon', 'why_underrated': 'Lunar violet'},
    {'name': 'Coral Abyss', 'hex': '#0A1F22', 'vibe': 'Sea coral', 'why_underrated': 'Abyssal pink'},
    {'name': 'Amber Eclipse', 'hex': '#132326', 'vibe': 'Sunset void', 'why_underrated': 'Golden ash'},
    {'name': 'Platinum Teal', 'hex': '#18292A', 'vibe': 'Industrial', 'why_underrated': 'Steel glow'},
    {'name': 'Quicksilver Teal', 'hex': '#0E1D1F', 'vibe': 'Liquid metal', 'why_underrated': 'Alchemist'},
    {'name': 'Meteor Teal', 'hex': '#112123', 'vibe': 'Shooting star', 'why_underrated': 'Celestial trail'},
    {'name': 'Graphite Rose', 'hex': '#152728', 'vibe': 'Pencil rose', 'why_underrated': 'Artist silver'},
    {'name': 'Chrome Teal', 'hex': '#1D2F30', 'vibe': 'Mirror finish', 'why_underrated': 'Automotive'},
    {'name': 'Pewter Teal', 'hex': '#0B2123', 'vibe': 'Ancient coin', 'why_underrated': 'Medieval silver'},
    {'name': 'Argent Teal', 'hex': '#162D2E', 'vibe': 'Heraldic', 'why_underrated': 'Knight armor'},
    {'name': 'Iridium Teal', 'hex': '#081A1C', 'vibe': 'Rare metal', 'why_underrated': 'Spacecraft'},
    {'name': 'Sterling Teal', 'hex': '#1A3435', 'vibe': 'Jewelry', 'why_underrated': 'Luxury teal'},
    {'name': 'Moonstone Teal', 'hex': '#0D2527', 'vibe': 'Gemstone', 'why_underrated': 'Mystical silver'},
    {'name': 'Galvanized Teal', 'hex': '#132E2F', 'vibe': 'Rusty silver', 'why_underrated': 'Industrial chic'},
    {'name': 'Electrum Teal', 'hex': '#10292B', 'vibe': 'Gold alloy', 'why_underrated': 'Ancient currency'},
    {'name': 'Silver Birch Teal', 'hex': '#182F30', 'vibe': 'Winter bark', 'why_underrated': 'Nordic silver'},
    {'name': 'Ultimate Void', 'hex': '#050F10', 'vibe': 'Event horizon', 'why_underrated': 'Cosmic absolute'},
    {'name': 'Singularity Teal', 'hex': '#000000', 'vibe': 'Black hole', 'why_underrated': 'Ultimate mystery'},
    {'name': 'Pearl Teal', 'hex': '#B8E6E0', 'vibe': 'Oyster pearl', 'why_underrated': 'Luminous shell'},
    {'name': 'Seafoam Rose', 'hex': '#93E9BE', 'vibe': 'Breaking wave', 'why_underrated': 'Coastal foam'},
    {'name': 'Jade Whisper', 'hex': '#A7D9A8', 'vibe': 'Temple jade', 'why_underrated': 'Asian serenity'},
    {'name': 'Lagoon Pearl', 'hex': '#66D7D4', 'vibe': 'Tropical lagoon', 'why_underrated': 'Island paradise'},
    {'name': 'Mint Glacier', 'hex': '#B2F2E4', 'vibe': 'Iceberg mint', 'why_underrated': 'Polar cap'},
    {'name': 'Coral Reef Gold', 'hex': '#4DD0E4', 'vibe': 'Shallow reef', 'why_underrated': 'Marine gold'},
    {'name': 'Emerald Mist', 'hex': '#50C878', 'vibe': 'Forest mist', 'why_underrated': 'Celtic emerald'},
    {'name': 'Sapphire Lagoon', 'hex': '#0F52BA', 'vibe': 'Deep lagoon', 'why_underrated': 'Sapphire gem'},
    {'name': 'Lichen Gold', 'hex': '#8FBC8F', 'vibe': 'Tree lichen', 'why_underrated': 'Woodland gold'},
    {'name': 'Aquamarine Rose', 'hex': '#7FFFD4', 'vibe': 'Gem rose', 'why_underrated': 'Precious stone'},
    {'name': 'Olive Teal', 'hex': '#6B8E23', 'vibe': 'Herb garden', 'why_underrated': 'Medieval dye'},
    {'name': 'Cobalt Teal', 'hex': '#0047AB', 'vibe': 'Deep ocean', 'why_underrated': 'Artist pigment'},
    {'name': 'Fern Rose', 'hex': '#4F7942', 'vibe': 'Forest fern', 'why_underrated': 'Woodland rose'},
    {'name': 'Indigo Reef', 'hex': '#4B0082', 'vibe': 'Purple reef', 'why_underrated': 'Royal indigo'},
    {'name': 'Honeydew Teal', 'hex': '#F0FFF0', 'vibe': 'Dewdrop', 'why_underrated': 'Morning honey'},
    {'name': 'Teal Velvet', 'hex': '#008080', 'vibe': 'Rich velvet', 'why_underrated': 'Luxury fabric'},
    {'name': 'Aurora Teal', 'hex': '#00FFFF', 'vibe': 'Northern lights', 'why_underrated': 'Polar aurora'},
    {'name': 'Basil Rose', 'hex': '#2E8B57', 'vibe': 'Herb rose', 'why_underrated': 'Italian garden'},
    {'name': 'Cerulean Gold', 'hex': '#007BA7', 'vibe': 'Sky gold', 'why_underrated': 'Painter classic'},
    {'name': 'Pistachio Teal', 'hex': '#93C572', 'vibe': 'Nut rose', 'why_underrated': 'Mediterranean'},
    {'name': 'Prussian Blue', 'hex': '#003153', 'vibe': 'Historical blue', 'why_underrated': 'Artist secret'},
    {'name': 'Sea Glass Rose', 'hex': '#98FF98', 'vibe': 'Beach glass', 'why_underrated': 'Ocean treasure'},
    {'name': 'Thyme Gold', 'hex': '#8FBC8F', 'vibe': 'Herb gold', 'why_underrated': 'Culinary rose'},
    {'name': 'Ultramarine Teal', 'hex': '#120A8F', 'vibe': 'Gem blue', 'why_underrated': 'Renaissance'},
    {'name': 'Willow Rose', 'hex': '#20B2AA', 'vibe': 'Tree willow', 'why_underrated': 'Riverbank rose'},
    {'name': 'Zaffre Teal', 'hex': '#0014A8', 'vibe': 'Deep zaffre', 'why_underrated': 'Rare pigment'},
    {'name': 'Alabaster Teal', 'hex': '#F2F0F5', 'vibe': 'Marble rose', 'why_underrated': 'Ancient stone'},
    {'name': 'Beryl Gold', 'hex': '#68E8C7', 'vibe': 'Gem gold', 'why_underrated': 'Mineral rose'},
    {'name': 'Chalcedony Rose', 'hex': '#66D7D4', 'vibe': 'Stone rose', 'why_underrated': 'Ancient gem'},
    {'name': 'Dolphin Teal', 'hex': '#2B7A78', 'vibe': 'Ocean mammal', 'why_underrated': 'Marine gold'},
    {'name': 'Eel Gold', 'hex': '#006994', 'vibe': 'River eel', 'why_underrated': 'Slippery rose'},
    {'name': 'Flint Teal', 'hex': '#6E7B8B', 'vibe': 'Stone flint', 'why_underrated': 'Prehistoric'},
    {'name': 'Glaucous Rose', 'hex': '#789ABC', 'vibe': 'Sky rose', 'why_underrated': 'Botanical term'},
    {'name': 'Hawk Teal', 'hex': '#7BA05B', 'vibe': 'Bird hawk', 'why_underrated': 'Forest gold'},
    {'name': 'Iris Rose', 'hex': '#5A67D8', 'vibe': 'Flower rose', 'why_underrated': 'Purple petal'},
    {'name': 'Jadeite Gold', 'hex': '#00A86B', 'vibe': 'Gem gold', 'why_underrated': 'Burmese jade'},
    {'name': 'Kingfisher Teal', 'hex': '#0B7B56', 'vibe': 'Bird teal', 'why_underrated': 'River king'},
    {'name': 'Lapis Rose', 'hex': '#26619C', 'vibe': 'Stone rose', 'why_underrated': 'Egyptian blue'},
    {'name': 'Mermaid Teal', 'hex': '#30D5C8', 'vibe': 'Mythical rose', 'why_underrated': 'Ocean legend'},
    {'name': 'Nacre Gold', 'hex': '#E8F5E8', 'vibe': 'Pearl gold', 'why_underrated': 'Mother shell'},
    {'name': 'Opal Teal', 'hex': '#A8C3BC', 'vibe': 'Gem opal', 'why_underrated': 'Iridescent'},
    {'name': 'Peacock Rose', 'hex': '#33A1C9', 'vibe': 'Bird rose', 'why_underrated': 'Feather display'},
    {'name': 'Quartz Teal', 'hex': '#008B8B', 'vibe': 'Crystal gold', 'why_underrated': 'Mineral vein'},
    {'name': 'Raven Rose', 'hex': '#181818', 'vibe': 'Bird raven', 'why_underrated': 'Gothic black'},
    {'name': 'Salmon Teal', 'hex': '#FF91A4', 'vibe': 'Fish rose', 'why_underrated': 'Pink salmon'},
    {'name': 'Topaz Gold', 'hex': '#FFC87C', 'vibe': 'Gem gold', 'why_underrated': 'November birthstone'},
    {'name': 'Umber Teal', 'hex': '#635147', 'vibe': 'Earth rose', 'why_underrated': 'Natural pigment'},
    {'name': 'Vermilion Teal', 'hex': '#CC474F', 'vibe': 'Red teal', 'why_underrated': 'Cinnabar'},
    {'name': 'Wisteria Rose', 'hex': '#C9A0DC', 'vibe': 'Flower rose', 'why_underrated': 'Purple bloom'},
    {'name': 'Xanthic Teal', 'hex': '#EEB422', 'vibe': 'Yellow gold', 'why_underrated': 'Citrus teal'},
    {'name': 'Yew Rose', 'hex': '#07393C', 'vibe': 'Tree rose', 'why_underrated': 'Ancient yew'},
    {'name': 'Zinc Teal', 'hex': '#1A3633', 'vibe': 'Metal rose', 'why_underrated': 'Industrial'},

    # 137-230: DIVERSE RED/YELLOW/SILVER/PINK/ORANGE/PURPLE (ASSUMED ORIGINAL 94)
    {'name': 'Rose Quartz', 'hex': '#F7CAC9', 'vibe': 'Gentle gem', 'why_underrated': 'Soft romance'},
    {'name': 'Saffron Veil', 'hex': '#F5A623', 'vibe': 'Spiced silk', 'why_underrated': 'Exotic warmth'},
    {'name': 'Silver Mist', 'hex': '#C0C0C0', 'vibe': 'Foggy sheen', 'why_underrated': 'Subtle metallic'},
    {'name': 'Blush Pink', 'hex': '#FFC1CC', 'vibe': 'Cheek flush', 'why_underrated': 'Delicate charm'},
    {'name': 'Tangerine Glow', 'hex': '#FF9F00', 'vibe': 'Citrus burst', 'why_underrated': 'Zesty vibrance'},
    {'name': 'Amethyst Haze', 'hex': '#9B59B6', 'vibe': 'Mystic purple', 'why_underrated': 'Spiritual glow'},
    {'name': 'Crimson Tide', 'hex': '#DC143C', 'vibe': 'Ocean wave', 'why_underrated': 'Bold passion'},
    {'name': 'Goldenrod', 'hex': '#DAA520', 'vibe': 'Autumn field', 'why_underrated': 'Harvest gold'},
    {'name': 'Platinum Glow', 'hex': '#E5E4E2', 'vibe': 'Luxury metal', 'why_underrated': 'Refined sheen'},
    {'name': 'Hot Pink', 'hex': '#FF69B4', 'vibe': 'Electric vibe', 'why_underrated': 'Playful pop'},
    {'name': 'Burnt Orange', 'hex': '#CC5500', 'vibe': 'Ember glow', 'why_underrated': 'Fiery earth'},
    {'name': 'Royal Purple', 'hex': '#7851A9', 'vibe': 'Regal cloak', 'why_underrated': 'Majestic depth'},
    {'name': 'Scarlet Flame', 'hex': '#FF2400', 'vibe': 'Blazing fire', 'why_underrated': 'Intense spark'},
    {'name': 'Canary Yellow', 'hex': '#FFFF99', 'vibe': 'Bird song', 'why_underrated': 'Cheerful light'},
    {'name': 'Steel Gray', 'hex': '#4682B4', 'vibe': 'Industrial sky', 'why_underrated': 'Modern cool'},
    {'name': 'Cotton Candy', 'hex': '#FFBCD9', 'vibe': 'Sweet fluff', 'why_underrated': 'Nostalgic pink'},
    {'name': 'Apricot', 'hex': '#FBCEB1', 'vibe': 'Soft fruit', 'why_underrated': 'Gentle warmth'},
    {'name': 'Lavender Mist', 'hex': '#E6E6FA', 'vibe': 'Floral haze', 'why_underrated': 'Soothing purple'},
    {'name': 'Ruby Glow', 'hex': '#E0115F', 'vibe': 'Gem fire', 'why_underrated': 'Passionate red'},
    {'name': 'Sunflower', 'hex': '#FFC107', 'vibe': 'Bright bloom', 'why_underrated': 'Sunny joy'},
    {'name': 'Silver Lining', 'hex': '#BFC1C2', 'vibe': 'Hopeful gleam', 'why_underrated': 'Optimistic gray'},
    {'name': 'Fuchsia Pop', 'hex': '#FF00FF', 'vibe': 'Vivid burst', 'why_underrated': 'Bold flair'},
    {'name': 'Coral Sunset', 'hex': '#FF7F50', 'vibe': 'Tropical dusk', 'why_underrated': 'Warm horizon'},
    {'name': 'Violet Bloom', 'hex': '#EE82EE', 'vibe': 'Flower burst', 'why_underrated': 'Vibrant purple'},
    {'name': 'Cherry Red', 'hex': '#D2042D', 'vibe': 'Fruit ripe', 'why_underrated': 'Lush sweetness'},
    {'name': 'Dandelion', 'hex': '#FFD700', 'vibe': 'Weed wish', 'why_underrated': 'Playful yellow'},
    {'name': 'Iron Gray', 'hex': '#43464B', 'vibe': 'Forged metal', 'why_underrated': 'Rugged strength'},
    {'name': 'Peach Puff', 'hex': '#FFDAB9', 'vibe': 'Soft fruit', 'why_underrated': 'Gentle glow'},
    {'name': 'Mandarin', 'hex': '#F28C38', 'vibe': 'Citrus zest', 'why_underrated': 'Tangy energy'},
    {'name': 'Lilac Breeze', 'hex': '#C8A2C8', 'vibe': 'Floral wind', 'why_underrated': 'Delicate purple'},
    {'name': 'Garnet Red', 'hex': '#733635', 'vibe': 'Deep jewel', 'why_underrated': 'Rich elegance'},
    {'name': 'Marigold', 'hex': '#EAA221', 'vibe': 'Golden bloom', 'why_underrated': 'Festive yellow'},
    {'name': 'Slate Silver', 'hex': '#708090', 'vibe': 'Rock sheen', 'why_underrated': 'Natural cool'},
    {'name': 'Bubblegum Pink', 'hex': '#F58092', 'vibe': 'Candy chew', 'why_underrated': 'Youthful fun'},
    {'name': 'Amber Sunset', 'hex': '#FF8C00', 'vibe': 'Evening glow', 'why_underrated': 'Warm dusk'},
    {'name': 'Plum Velvet', 'hex': '#800080', 'vibe': 'Rich fabric', 'why_underrated': 'Luxury purple'},
    {'name': 'Firebrick', 'hex': '#B22222', 'vibe': 'Burning clay', 'why_underrated': 'Earthy red'},
    {'name': 'Lemon Chiffon', 'hex': '#FFFACD', 'vibe': 'Soft citrus', 'why_underrated': 'Light dessert'},
    {'name': 'Charcoal Gray', 'hex': '#36454F', 'vibe': 'Smoky depth', 'why_underrated': 'Moody neutral'},
    {'name': 'Blossom Pink', 'hex': '#FFB6C1', 'vibe': 'Flower petal', 'why_underrated': 'Soft romance'},
    {'name': 'Persimmon', 'hex': '#EC5800', 'vibe': 'Autumn fruit', 'why_underrated': 'Seasonal warmth'},
    {'name': 'Orchid Glow', 'hex': '#DA70D6', 'vibe': 'Exotic bloom', 'why_underrated': 'Vibrant purple'},
    {'name': 'Brick Red', 'hex': '#CB4154', 'vibe': 'Urban wall', 'why_underrated': 'Rustic charm'},
    {'name': 'Buttercup', 'hex': '#F0C05A', 'vibe': 'Field flower', 'why_underrated': 'Sunny charm'},
    {'name': 'Ash Gray', 'hex': '#B2BEB5', 'vibe': 'Soft smoke', 'why_underrated': 'Calm neutral'},
    {'name': 'Sakura Pink', 'hex': '#FFB7C5', 'vibe': 'Cherry blossom', 'why_underrated': 'Japanese spring'},
    {'name': 'Clementine', 'hex': '#E96E00', 'vibe': 'Citrus burst', 'why_underrated': 'Zesty orange'},
    {'name': 'Mauve Shadow', 'hex': '#915F6D', 'vibe': 'Dusty purple', 'why_underrated': 'Victorian charm'},
    {'name': 'Carmine Red', 'hex': '#960018', 'vibe': 'Deep blood', 'why_underrated': 'Intense depth'},
    {'name': 'Cornsilk', 'hex': '#FFF8DC', 'vibe': 'Soft maize', 'why_underrated': 'Gentle yellow'},
    {'name': 'Pewter Gray', 'hex': '#96A8A8', 'vibe': 'Aged metal', 'why_underrated': 'Subtle sheen'},
    {'name': 'Flamingo Pink', 'hex': '#FC8EAC', 'vibe': 'Bird feather', 'why_underrated': 'Tropical flair'},
    {'name': 'Carrot Orange', 'hex': '#ED9121', 'vibe': 'Root glow', 'why_underrated': 'Garden warmth'},
    {'name': 'Indigo Night', 'hex': '#4B0082', 'vibe': 'Starry sky', 'why_underrated': 'Mystic purple'},
    {'name': 'Sangria Red', 'hex': '#92000A', 'vibe': 'Wine sip', 'why_underrated': 'Rich drink'},
    {'name': 'Honey Yellow', 'hex': '#FFB300', 'vibe': 'Sweet nectar', 'why_underrated': 'Natural glow'},
    {'name': 'Fog Gray', 'hex': '#D3D3D3', 'vibe': 'Morning mist', 'why_underrated': 'Ethereal neutral'},
    {'name': 'Candy Pink', 'hex': '#E4717A', 'vibe': 'Sugar sweet', 'why_underrated': 'Playful treat'},
    {'name': 'Papaya Whip', 'hex': '#FFEFD5', 'vibe': 'Tropical cream', 'why_underrated': 'Soft exotic'},
    {'name': 'Eggplant Purple', 'hex': '#614051', 'vibe': 'Vegetable rind', 'why_underrated': 'Deep culinary'},
    {'name': 'Tomato Red', 'hex': '#FF6347', 'vibe': 'Ripe fruit', 'why_underrated': 'Vivid harvest'},
    {'name': 'Mango Tango', 'hex': '#FF8243', 'vibe': 'Tropical dance', 'why_underrated': 'Exotic rhythm'},
    {'name': 'Periwinkle', 'hex': '#CCCCFF', 'vibe': 'Soft flower', 'why_underrated': 'Gentle purple'},
    {'name': 'Claret Red', 'hex': '#7F1734', 'vibe': 'Wine depth', 'why_underrated': 'Rich vintage'},
    {'name': 'Saffron Glow', 'hex': '#F4C430', 'vibe': 'Spice shine', 'why_underrated': 'Exotic yellow'},
    {'name': 'Mist Gray', 'hex': '#C4C4C4', 'vibe': 'Cloud veil', 'why_underrated': 'Soft neutral'},
    {'name': 'Rose Petal', 'hex': '#F08080', 'vibe': 'Floral blush', 'why_underrated': 'Romantic pink'},
    {'name': 'Sienna Earth', 'hex': '#A0522D', 'vibe': 'Clay ground', 'why_underrated': 'Natural warmth'},
    {'name': 'Lilac Glow', 'hex': '#DDA0DD', 'vibe': 'Floral light', 'why_underrated': 'Soft purple'},
    {'name': 'Chili Red', 'hex': '#C21E56', 'vibe': 'Spicy kick', 'why_underrated': 'Fiery zest'},
    {'name': 'Banana Yellow', 'hex': '#FFE135', 'vibe': 'Fruit ripe', 'why_underrated': 'Tropical cheer'},
    {'name': 'Smoke Gray', 'hex': '#708090', 'vibe': 'Hazy air', 'why_underrated': 'Moody neutral'},
    {'name': 'Bubble Pink', 'hex': '#FF92A9', 'vibe': 'Candy fizz', 'why_underrated': 'Playful pop'},
    {'name': 'Pumpkin Orange', 'hex': '#FF7518', 'vibe': 'Fall harvest', 'why_underrated': 'Autumn glow'},
    {'name': 'Violet Haze', 'hex': '#8A2BE2', 'vibe': 'Mystic fog', 'why_underrated': 'Dreamy purple'},
    {'name': 'Oxide Red', 'hex': '#8B0000', 'vibe': 'Rusty metal', 'why_underrated': 'Industrial red'},
    {'name': 'Mustard Yellow', 'hex': '#FFDB58', 'vibe': 'Spicy seed', 'why_underrated': 'Bold flavor'},
    {'name': 'Tin Gray', 'hex': '#918C8C', 'vibe': 'Metal sheen', 'why_underrated': 'Subtle metallic'},
    {'name': 'Magenta Glow', 'hex': '#CA2C92', 'vibe': 'Vivid pulse', 'why_underrated': 'Electric pink'},
    {'name': 'Terracotta', 'hex': '#E2725B', 'vibe': 'Clay earth', 'why_underrated': 'Ancient craft'},
    {'name': 'Amethyst Shine', 'hex': '#9966CC', 'vibe': 'Gem sparkle', 'why_underrated': 'Mystic purple'},
    {'name': 'Berry Red', 'hex': '#9B1D64', 'vibe': 'Fruit juice', 'why_underrated': 'Rich tart'},
    {'name': 'Gold Leaf', 'hex': '#FFD700', 'vibe': 'Precious metal', 'why_underrated': 'Luxury yellow'},
    {'name': 'Silver Veil', 'hex': '#C9C0BB', 'vibe': 'Soft sheen', 'why_underrated': 'Gentle metallic'},
    {'name': 'Pink Frosting', 'hex': '#FF99CC', 'vibe': 'Sweet icing', 'why_underrated': 'Dessert charm'},
    {'name': 'Sienna Glow', 'hex': '#A0522D', 'vibe': 'Earthy shine', 'why_underrated': 'Warm depth'},
    {'name': 'Purple Mist', 'hex': '#A100A1', 'vibe': 'Enigmatic fog', 'why_underrated': 'Mystic purple'},

    # NEW ADDITIONS: 100+ UNIQUE COLORS WITH FEW SIMILARS
    # RARE REDS (deep, rusty, uncommon shades)
    {'name': 'Crimson Shadow', 'hex': '#4A0404', 'vibe': 'Velvet night', 'why_underrated': 'Gothic depth'},
    {'name': 'Rusty Garnet', 'hex': '#5E1914', 'vibe': 'Aged wine', 'why_underrated': 'Vintage rust'},
    {'name': 'Blood Orange Red', 'hex': '#8B0000', 'vibe': 'Fiery core', 'why_underrated': 'Intense heat'},
    {'name': 'Mahogany Ember', 'hex': '#420D09', 'vibe': 'Burning wood', 'why_underrated': 'Forest fire'},
    {'name': 'Scarlet Whisper', 'hex': '#990F02', 'vibe': 'Faint echo', 'why_underrated': 'Subtle passion'},
    {'name': 'Brick Dust Red', 'hex': '#B22222', 'vibe': 'Urban decay', 'why_underrated': 'Industrial grit'},
    {'name': 'Cherry Pit', 'hex': '#3B0910', 'vibe': 'Hidden seed', 'why_underrated': 'Dark fruit'},
    {'name': 'Ruby Abyss', 'hex': '#300000', 'vibe': 'Deep gem', 'why_underrated': 'Infinite red'},
    {'name': 'Sanguine Veil', 'hex': '#660000', 'vibe': 'Mystical blood', 'why_underrated': 'Ancient ritual'},
    {'name': 'Cardinal Feather', 'hex': '#C41E3A', 'vibe': 'Bird plume', 'why_underrated': 'Ecclesiastical'},
    {'name': 'Vermilion Rust', 'hex': '#D9381E', 'vibe': 'Oxidized metal', 'why_underrated': 'Alchemical'},
    {'name': 'Pomegranate Core', 'hex': '#4C0000', 'vibe': 'Fruit heart', 'why_underrated': 'Exotic seed'},
    {'name': 'Maroon Eclipse', 'hex': '#800000', 'vibe': 'Shadowed moon', 'why_underrated': 'Celestial red'},
    {'name': 'Falun Red', 'hex': '#7D2027', 'vibe': 'Swedish barn', 'why_underrated': 'Folk pigment'},
    {'name': 'Alizarin Crimson', 'hex': '#E32636', 'vibe': 'Artist dye', 'why_underrated': 'Historical red'},
    {'name': 'Cordovan Leather', 'hex': '#893F45', 'vibe': 'Spanish hide', 'why_underrated': 'Luxury tan'},

    # VIBRANT YELLOWS (saffron, mustard, uncommon brights/dulls)
    {'name': 'Saffron Thread', 'hex': '#F4C430', 'vibe': 'Spice silk', 'why_underrated': 'Exotic gold'},
    {'name': 'Mustard Seed', 'hex': '#DAA520', 'vibe': 'Earthy spice', 'why_underrated': 'Biblical yellow'},
    {'name': 'Lemon Zest', 'hex': '#FFF44F', 'vibe': 'Citrus peel', 'why_underrated': 'Tangy bright'},
    {'name': 'Amber Resin', 'hex': '#FFBF00', 'vibe': 'Fossilized glow', 'why_underrated': 'Prehistoric'},
    {'name': 'Chartreuse Fog', 'hex': '#DFFF00', 'vibe': 'Liqueur mist', 'why_underrated': 'Monk secret'},
    {'name': 'Cadmium Yellow', 'hex': '#FFF600', 'vibe': 'Pigment pure', 'why_underrated': 'Artist bold'},
    {'name': 'Butterscotch Drip', 'hex': '#E4B85A', 'vibe': 'Candy melt', 'why_underrated': 'Sweet warmth'},
    {'name': 'Gamboge Gum', 'hex': '#E49B0F', 'vibe': 'Tree resin', 'why_underrated': 'Asian dye'},
    {'name': 'Naples Yellow', 'hex': '#FADA5E', 'vibe': 'Italian sun', 'why_underrated': 'Renaissance'},
    {'name': 'Orpiment Mineral', 'hex': '#E9C46A', 'vibe': 'Arsenic glow', 'why_underrated': 'Ancient poison'},
    {'name': 'Jonquil Bloom', 'hex': '#F4CA16', 'vibe': 'Daffodil petal', 'why_underrated': 'Spring flower'},
    {'name': 'Banana Mania', 'hex': '#FAE7B5', 'vibe': 'Fruit peel', 'why_underrated': 'Playful pale'},
    {'name': 'Mikado Yellow', 'hex': '#FFC40C', 'vibe': 'Japanese emperor', 'why_underrated': 'Royal bright'},
    {'name': 'Selective Yellow', 'hex': '#FFBA00', 'vibe': 'Signal light', 'why_underrated': 'Safety glow'},
    {'name': 'School Bus Yellow', 'hex': '#FFD800', 'vibe': 'Iconic ride', 'why_underrated': 'Childhood memory'},

    # SUBTLE SILVERS/GRAYS (metallic, foggy, unique neutrals)
    {'name': 'Quicksilver Mercury', 'hex': '#A9A9A9', 'vibe': 'Liquid metal', 'why_underrated': 'Alchemist silver'},
    {'name': 'Foggy Platinum', 'hex': '#E5E4E2', 'vibe': 'Misty jewel', 'why_underrated': 'Luxury fog'},
    {'name': 'Gunmetal Sheen', 'hex': '#2A3439', 'vibe': 'Weapon polish', 'why_underrated': 'Industrial gray'},
    {'name': 'Pewter Patina', 'hex': '#8A9597', 'vibe': 'Aged alloy', 'why_underrated': 'Antique silver'},
    {'name': 'Nickel Ore', 'hex': '#727472', 'vibe': 'Mineral vein', 'why_underrated': 'Earth metal'},
    {'name': 'Davys Grey', 'hex': '#555555', 'vibe': 'Artist slate', 'why_underrated': 'Watercolor neutral'},
    {'name': 'Paynes Grey', 'hex': '#536878', 'vibe': 'Painter mix', 'why_underrated': 'Moody blue-gray'},
    {'name': 'Roman Silver', 'hex': '#838996', 'vibe': 'Coin patina', 'why_underrated': 'Empire relic'},
    {'name': 'Sonic Silver', 'hex': '#757575', 'vibe': 'Hedgehog fur', 'why_underrated': 'Gamer icon'},
    {'name': 'Manatee Gray', 'hex': '#979AAA', 'vibe': 'Sea mammal', 'why_underrated': 'Ocean neutral'},
    {'name': 'Cadet Grey', 'hex': '#91A3B0', 'vibe': 'Military uniform', 'why_underrated': 'Subtle discipline'},
    {'name': 'Battleship Grey', 'hex': '#848482', 'vibe': 'Naval hull', 'why_underrated': 'Warship stealth'},
    {'name': 'Old Silver', 'hex': '#848482', 'vibe': 'Tarnished coin', 'why_underrated': 'Vintage luster'},
    {'name': 'Quick Silver', 'hex': '#A6A6A6', 'vibe': 'Mythical speed', 'why_underrated': 'God metal'},
    {'name': 'Silver Chalice', 'hex': '#ACACAC', 'vibe': 'Holy grail', 'why_underrated': 'Legendary artifact'},

    # BOLD PINKS (neon, muted, unique magentas)
    {'name': 'Neon Fuchsia', 'hex': '#FE4164', 'vibe': 'Electric bloom', 'why_underrated': '80s glow'},
    {'name': 'Muted Magenta', 'hex': '#D33682', 'vibe': 'Soft velvet', 'why_underrated': 'Subtle passion'},
    {'name': 'Bubblegum Burst', 'hex': '#FF69B4', 'vibe': 'Candy pop', 'why_underrated': 'Playful chew'},
    {'name': 'Razzmatazz', 'hex': '#E3256B', 'vibe': 'Showbiz flash', 'why_underrated': 'Theatrical pink'},
    {'name': 'Telemagenta', 'hex': '#CF3476', 'vibe': 'TV signal', 'why_underrated': 'Broadcast bold'},
    {'name': 'Wild Orchid', 'hex': '#D470A2', 'vibe': 'Exotic flower', 'why_underrated': 'Tropical pink'},
    {'name': 'Charm Pink', 'hex': '#E68FAC', 'vibe': 'Enchanting hue', 'why_underrated': 'Magical allure'},
    {'name': 'Thulian Pink', 'hex': '#DE6FA1', 'vibe': 'Martian dust', 'why_underrated': 'Sci-fi planet'},
    {'name': 'Kobi Pink', 'hex': '#E79EC9', 'vibe': 'Dog breed', 'why_underrated': 'Canine soft'},
    {'name': 'Amaranth Pink', 'hex': '#F19CBB', 'vibe': 'Eternal flower', 'why_underrated': 'Mythical bloom'},
    {'name': 'Persian Rose', 'hex': '#FE28A2', 'vibe': 'Empire petal', 'why_underrated': 'Oriental pink'},
    {'name': 'China Rose', 'hex': '#A8516E', 'vibe': 'Asian bloom', 'why_underrated': 'Cultural muted'},
    {'name': 'Mystic Maroon Pink', 'hex': '#AD5A5A', 'vibe': 'Enigmatic shade', 'why_underrated': 'Deep mystery'},
    {'name': 'Brilliant Rose', 'hex': '#FF55A3', 'vibe': 'Dazzling petal', 'why_underrated': 'Vivid flower'},
    {'name': 'French Rose', 'hex': '#F64A8A', 'vibe': 'Parisian chic', 'why_underrated': 'Fashion icon'},

    # WARM ORANGES (terracotta, citrus, unique earthies)
    {'name': 'Terracotta Clay', 'hex': '#E2725B', 'vibe': 'Pottery earth', 'why_underrated': 'Ancient craft'},
    {'name': 'Citrus Peel', 'hex': '#FFA500', 'vibe': 'Orange rind', 'why_underrated': 'Zesty fresh'},
    {'name': 'Burnt Sienna', 'hex': '#E97451', 'vibe': 'Italian earth', 'why_underrated': 'Renaissance pigment'},
    {'name': 'Persimmon Fruit', 'hex': '#EC5800', 'vibe': 'Autumn harvest', 'why_underrated': 'Seasonal orange'},
    {'name': 'Carrot Rust', 'hex': '#ED9121', 'vibe': 'Root vegetable', 'why_underrated': 'Garden glow'},
    {'name': 'Alloy Orange', 'hex': '#C46210', 'vibe': 'Metal blend', 'why_underrated': 'Industrial warm'},
    {'name': 'Fulvous Duck', 'hex': '#E48400', 'vibe': 'Bird plumage', 'why_underrated': 'Ornithology orange'},
    {'name': 'Ginger Root', 'hex': '#BF642F', 'vibe': 'Spice rhizome', 'why_underrated': 'Culinary earth'},
    {'name': 'Tangerine Dream', 'hex': '#F28500', 'vibe': 'Citrus fantasy', 'why_underrated': 'Band-inspired'},
    {'name': 'Bronze Orange', 'hex': '#CD7F32', 'vibe': 'Medal sheen', 'why_underrated': 'Olympic glow'},
    {'name': 'Apricot Pit', 'hex': '#FBCEB1', 'vibe': 'Stone fruit', 'why_underrated': 'Pale warm'},
    {'name': 'Mandarin Peel', 'hex': '#FF8243', 'vibe': 'Chinese citrus', 'why_underrated': 'Festive orange'},
    {'name': 'Pumpkin Spice', 'hex': '#D2691E', 'vibe': 'Fall latte', 'why_underrated': 'Seasonal blend'},
    {'name': 'Tawny Owl', 'hex': '#804000', 'vibe': 'Bird feather', 'why_underrated': 'Nocturnal earth'},
    {'name': 'Yam Orange', 'hex': '#D76B00', 'vibe': 'Root tuber', 'why_underrated': 'African harvest'},

    # DEEP PURPLES (amethyst, eggplant, unique violets)
    {'name': 'Amethyst Crystal', 'hex': '#9966FF', 'vibe': 'Gem facet', 'why_underrated': 'Healing stone'},
    {'name': 'Eggplant Skin', 'hex': '#614051', 'vibe': 'Vegetable rind', 'why_underrated': 'Culinary deep'},
    {'name': 'Byzantine Purple', 'hex': '#BD33A4', 'vibe': 'Empire dye', 'why_underrated': 'Historical royal'},
    {'name': 'Tyrian Purple', 'hex': '#66023C', 'vibe': 'Snail ink', 'why_underrated': 'Ancient luxury'},
    {'name': 'Mauve Mist', 'hex': '#E0B0FF', 'vibe': 'Flower haze', 'why_underrated': 'Victorian soft'},
    {'name': 'Heliotrope Bloom', 'hex': '#DF73FF', 'vibe': 'Sun-loving', 'why_underrated': 'Botanical purple'},
    {'name': 'Phlox Petal', 'hex': '#DF00FF', 'vibe': 'Garden flower', 'why_underrated': 'Vivid bloom'},
    {'name': 'Psychedelic Purple', 'hex': '#DF00FF', 'vibe': '60s trip', 'why_underrated': 'Hippie vibe'},
    {'name': 'Pomp and Power', 'hex': '#86608E', 'vibe': 'Regal show', 'why_underrated': 'Monarch purple'},
    {'name': 'Patriarch Purple', 'hex': '#800080', 'vibe': 'Church leader', 'why_underrated': 'Ecclesiastical'},
    {'name': 'Veronica Violet', 'hex': '#A020F0', 'vibe': 'Flower violet', 'why_underrated': 'Speedwell bloom'},
    {'name': 'Han Purple', 'hex': '#5218FA', 'vibe': 'Chinese pigment', 'why_underrated': 'Dynasty rare'},
    {'name': 'Palatinate Purple', 'hex': '#682860', 'vibe': 'German royal', 'why_underrated': 'University color'},
    {'name': 'Mardi Gras Purple', 'hex': '#8800AA', 'vibe': 'Festival bead', 'why_underrated': 'Carnival deep'},
    {'name': 'Electric Violet', 'hex': '#8F00FF', 'vibe': 'Neon charge', 'why_underrated': 'Energy surge'},
]
